window.Translators = {
  branch: {
    "downtown financial center": 1,
    "midtown business branch": 2,
    "waterfront branch": 3,
    "lakeside branch": 4,
    "airport business center": 5,
    "north hills branch": 6,
    "southridge branch": 7,
    "eastside branch": 8,
    "westlake branch": 9,
    "university district branch": 10,
    "tech park branch": 11,
    "riverfront branch": 12,
    "harborview branch": 13,
    "maple grove branch": 14,
    "cedar ridge branch": 15,
    "pinecrest branch": 16,
    "oak valley branch": 17,
    "willow creek branch": 18,
    "sunset boulevard branch": 19,
    "highland park branch": 20,
    "greenfield branch": 21,
    "stonebridge branch": 22,
    "brookside branch": 23,
    "parkview branch": 24,
    "crossroads branch": 25,
    "creekside branch": 26,
    "hillcrest branch": 27,
    "meadowbrook branch": 28,
    "riverside branch": 29,
    "timberline branch": 30,
    "gateway branch": 31,
    "prospect branch": 32,
    "heritage branch": 33,
    "liberty branch": 34,
    "capitol branch": 35,
    "main street branch": 36,
    "elm street branch": 37,
    "market square branch": 38,
    "union station branch": 39,
    "bayside branch": 40,
    "seaview branch": 41,
    "canal district branch": 42,
    "grand avenue branch": 43,
    "summit branch": 44,
    "redwood branch": 45,
    "sycamore branch": 46,
    "aspen branch": 47,
    "birchwood branch": 48,
    "copperfield branch": 49,
    "silver springs branch": 50,
    "meadowvale branch": 51
  }, 
  officer: {
    "John Doe": 1,
    "Jane Smith": 2,
    "Bob Johnson": 3,
    "Alice Brown": 4,
    "Charlie Davis": 5,
    "Diana Wilson": 6,
    "Ethan Miller": 7,
    "Fiona Garcia": 8,
    "George Rodriguez": 9,
    "Hannah Martinez": 12
  },
  _meta: {
    branch: { synonyms: ["branch", "branches", "location", "office"] },
    officer: { synonyms: ["officer", "officers", "rm", "relationship manager", "owner"] }
  }
};